### PR TITLE
Add spec for SwitchPoint.writable_all!

### PR DESCRIPTION
**Pull request by ppworks**
I want to know behavior of `SwitchPoint.writable_all` when using along with `with_readonly` method.

1. I added spec for `SwitchPoint.writable_all`
1. ~~I added `SwitchPoint.reset_all!` method to reset to default SwitchPoint::Proxy#mode.~~

### CODE REVIEW

**Comment by eagletmt** [comment]
Hmm, the gem's default SwitchPoint::Proxy#mode is always `:readonly` .
https://github.com/eagletmt/switch_point/blob/v0.8.0/lib/switch_point/proxy.rb#L17

You should use `readonly!`, `readonly_all!`, `writable!`, and `writable_all!` only in initialization phase to change the default mode.
For instance, put `SwitchPoint.writable!(:nanika3)` in config/initializers/switch_point.rb to change the default mode of `nanika3` .
Always use `with_*` methods in application code.

**Comment by eagletmt** [comment]
Test cases in https://github.com/eagletmt/switch_point/pull/12/commits/babd72a2b86acd2b7e0f5b97eb7921f01c43bc72 looks good, but skeptical of adding `reset!` and `reset_all!` .

**Comment by ppworks** [comment]
Thanks for your comment.

I've got it.`Nanika3`(without :readonly model) [always sends all queries to `:writable`](https://github.com/eagletmt/switch_point/blob/master/spec/switch_point/model_spec.rb#L149-L159) regardless of `SwitchPoint::Proxy#mode`, right?

I think it's better that I add following test.

```diff
diff --git a/spec/switch_point/model_spec.rb b/spec/switch_point/model_spec.rb
index 8cb62b8..b64aca1 100644
--- a/spec/switch_point/model_spec.rb
+++ b/spec/switch_point/model_spec.rb
@@ -154,6 +154,11 @@ RSpec.describe SwitchPoint::Model do
           Nanika3.create
         end
         expect(Nanika3.count).to eq(1)
+        Nanika3.with_readonly do
+          expect(Nanika3).to connect_to('comment_writable.sqlite3')
+          Nanika3.create
+        end
+        expect(Nanika3.count).to eq(2)
         expect(Nanika3.with_readonly { Nanika3.connection }).to equal(Nanika3.with_writable { Nanika3.connection })
       end
     end
```

Anyway, I've removed `reset!` and `reset_all!` commit.

Please check my PR again?

**Comment by eagletmt** [comment]
> I've got it.Nanika3(without :readonly model) always sends all queries to :writable regardless of SwitchPoint::Proxy#mode, right?

Right.

> I think it's better that I add test like the following.

It could make some sense, but the behavior in readonly mode is tested [right above it](https://github.com/eagletmt/switch_point/blob/v0.8.0/spec/switch_point/model_spec.rb#L151) because the default mode (i.e., without any with_* block) is readonly.

**Pull request merged**
